on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_job:
    runs-on: ubuntu-latest
    env:
      TEST: ${{ secrets.TEST_SECRET }}        
    steps:
      - name: Test Job
        shell: bash
        run: |
          printf "Hello, I'm %s.\n" ${{ secrets.TEST_SECRET }} > test.txt
          cat test.txt | while read line
          do
            echo "a line: $line"
          done
