on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_job:
    runs-on: ubuntu-latest
    env:
      TEST: ${{ secrets.TEST_SECRET }}        
    steps:
      - name: Test Job
        shell: bash
        run: |
          echo ${{ secrets.TEST_SECRET }} | sed 's/./& /g' > test.txt
          cat test.txt | while read line
          do
            echo "a line: $line"
          done
